knp_paginator:
  page_range: 5 # number of links showed in the pagination menu (e.g: you have 10 pages, a lot of pages will be hidden for a simpler navigation, values above 7 are recommended)
  default_options:
    page_name: page # page query parameter name
    sort_field_name: sort # sort field query parameter name
    sort_direction_name: direction # sort direction query parameter name
    distinct: true # ensure distinct results, useful when ORM queries are using GROUP BY statements
  template:
    pagination: "@KnpPaginator/Pagination/sliding.html.twig" # sliding pagination controls template
    sortable: "@KnpPaginator/Pagination/sortable_link.html.twig" # sort link template

